[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "kaleido==0.2.0",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "reportlab>=4.4.3",
    "scipy>=1.16.2",
    "streamlit>=1.49.1",
]
